---
title: "Curriculum vitae"
description: |
  Curriculum Vitae
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# GERMÁN D. SILVA

Ph.D. Candidate \| Department of Geography, University of California,
Santa Barbara \|
[german.silva\@geog.ucsb.edu](mailto:german.silva@geog.ucsb.edu){.email}

## EDUCATION

***Ph.D., Geography***, University of California, Santa Barbara &emsp; **Expected June 2025**<br> 
Committee: Jennifer King (Co-Chair), Dar Roberts (Co-Chair), Ian Walker, Kristin Byrd<br>
Research Interests: Wetland soil salinity, biogeochemistry, ecological monitoring <br>

***M.A., Geography***, University of California, Santa Barbara &emsp; **Aug. 2021**<br> 
Committee: Jennifer King (Co-Chair), Dar Roberts (Co-Chair), Joe McFadden<br> 
Research Interests: Wetland ecology, remote sensing, ecological disturbance<br> 
Thesis: “The Influence of the Montecito Debris Flows on Landcover in Carpinteria Salt Marsh”<br>

***B.A., Geography***, California State University, Stanislaus &emsp; **May 2019** <br> 
Honors: *Summa Cum Laude* <br>
Areas of Concentration: Physical/Environmental Geography and Geospatial Technology<br> 
Minor: Environmental and Resource Studies<br> 
Thesis: “Effect of California’s Drought on Pickleweed Vigor in a Californian Wetland: A Remote Sensing Approach”<br>

## PROFESSIONAL POSITIONS

*Graduate Research Fellow*, University of California, Santa Barbara &nbsp; **Sep. 2019 – Present** <br>
*Graduate Teaching Associate*, University of California, Santa Barbara &nbsp; **Aug. 2024 – Sep 2024** <br>
*Summer Research Fellow*, NASA/Caltech Jet Propulsion Lab  &nbsp; **June 2023 - Sep. 2023** <br>
*Graduate Teaching Assistant*, University of California, Santa Barbara &nbsp; **Sep. 2021 - Dec. 2021**<br>
*Campus Cartographer*, California State University, Stanislaus  &nbsp; **June 2017 – Aug. 2019**<br>


## TEACHING AND PEDAGOGICAL EXPERIENCE

### Instructor of Record

***GEOG W8 Intro to Global Warming*** &emsp; **Aug. 2024 – Sep. 2024** <br>
*University of California, Santa Barbara* <br>
Course provided students with an overview of global warming and climate change processes. Course focused on developing critical thinking and writing skills related to climate related topics from the physics of climate change to social, economic, and environmental impacts of climate change. Assignments included guided article discussions, AI and climate literacy, and personal reflection of climate change. <br>

### Teaching Assistant

***GEOG 176A Intro to Geographic Information Systems*** &emsp; **Sep. 2021 – Dec. 2021** <br> 
*University of California, Santa Barbara* <br> 
Course provided students with an introductory overview of the theory and techniques of geographic information systems. As a teaching associate, I
provided supplementary lectures of weekly topics, led weekly computer labs, and assisted students with GIS project design and execution for final projects. <br>

### Pedagogical Training

***Certificate in College and University Teaching*** &emsp; **Expected 2025** <br> 
*University of California, Santa Barbara* <br> 
The UCSB Certificate in College and University Teaching (CCUT) is designed for students who wish to demonstrate superior competence and experience in teaching at the university or college level. Certificate requirements include completion or attainment of several teaching-related skills and
experiences culminating in independent instruction of an entire course with the support of a UCSB faculty mentor. Requirements include development of course materials, the completion of an evidence-based pedagogical project, analysis of student evaluations, and more. <br>

***Certificate in Inclusive Teaching*** &emsp; **Expected 2025** <br>
*University of California, Santa Barbara* <br>  The Certificate in Inclusive Teaching (CIT) is designed for UCSB graduate students and postdocs, to help them foster inclusive classrooms, effectively mentor a diverse student body, and enhance their professional development. Students are required to attend and engage in workshops from the following categories: Course Design, Instruction, Mentorship & Student Support, Professional Development. <br>

***Summer Teaching Institute for Associates (STIA)*** &emsp; **Sep. 2024** <br> 
*University of California, Santa Barbara* <br> 
The UCSB Summer Teaching Institute for Associates (STIA) supports graduate student instructors who have responsibility for an undergraduate course during Summer Sessions. The STIA Associate has completed a series of online assignments, cooperative peer review, pedagogical skills training activities, and mentoring meetings with a UC faculty member. Specific topics include: course planning; syllabus design and review, student learning outcomes, course and lecture planning, giving lectures, active learning, designing and grading assessments, giving and receiving feedback on learning, issues common to first time instructors, online teaching and learning. <br>

## RESEARCH EXPERIENCE

***SBG High Frequency Timeseries (SHIFT)*** &emsp; **Feb.2022 – Sep. 2022**<br> 
*University of California, Santa Barbara*<br>
Research field campaign to collect wetland plant traits and soil salinity samples as part of the NASA Jet Propulsion Lab’s pathfinder campaign for the future Surface Biology and Geology sensors

## MENTORSHIP EXPERIENCE

### Graduate Student Peer Mentor

Sebastian Alvarez, *University of California, Santa Barbara*, PhD student &nbsp; **Aug. 2024 – Present** <br>
Wenxin Yang, *University of California, Santa Barbara*, PhD student &ensp; **Jan. 2024 – Present** <br>
Xue Yan, *University of California, Santa Barbara*, PhD student &ensp; **Jan. 2024 – Present** <br>
Sarah Payne, *University of California, Santa Barbara*, PhD student &ensp; **Oct. 2023 – Present** <br>
My-Thu Tran, *University of California Santa Barbara/San Diego State University*, PhD student &nbsp; **Oct. 2023 – May 2024** <br>

### Undergraduate Student Mentees (\* indicates independent project)

Damian Padilla, *University of California, Santa Barbara* &emsp; **Oct. 2024 – Present**<br>
Aidan Flynn, *University of California, Santa Barbara* &emsp;**Oct. 2024 – Present**<br>
Abby Nestor, *University of California, Santa Barbara* &emsp; **Oct. 2024 – Present**<br>
Danae Stathatos\*, *University of California, Santa Barbara* &emsp; **April. 2024 – Present**<br>
Kathryn Kolb\*, *University of California, Santa Barbara* &emsp; **Oct. 2023 – Present**<br>
Evelyn Tsang, *University of California, Santa Barbara* &emsp; **April 2024 – Sep. 2024**<br>
Marian Walker\*, *University of California, Santa Barbara* &emsp; **Jan. 2021 – March 2024** <br>
Ruiming Song, *University of California, Santa Barbara* &emsp; **April 2022 – Dec. 2022**<br>
Ella Phillips, *University of California, Santa Barbara* &emsp; **April 2022 – June 2022**<br>
Brianna Lee, *University of California, Santa Barbara* &emsp; **April 2022 – June 2022**<br>
Madi Arndt, *University of California, Santa Barbara* &emsp; **April 2022 – June 2022**<br>
Chenjia Liu, *University of California, Santa Barbara* &emsp; **Jan. 2022 – June 2022**<br>

## PUBLICATIONS

**In Review** &ensp; *Silva, G.D.*, Roberts, D.A., Byrd, K.B., Chadwick, K.D., Walker, I.J., and King, J.Y. “Using imaging spectroscopy and elevation in machine learning to estimate soil salinity in intermittently tidal wetlands.” *Ecosphere* <br>

**2022** &ensp; *Silva, G.D.*, Roberts, D.A., McFadden, J.P., King, J.Y.,
"Shifts in Salt Marsh Vegetation Landcover after Debris Flow
Deposition." *Remote Sensing* 14(12):2819.
<https://doi.org/10.3390/rs14122819> <br>

**2019** &ensp; *Silva, G.*, “Pickleweed Vigor in a Californian Salt Marsh: A
Remote Sensing Approach.” *Honors Program Journal of Exploratory Research.* <br>

## PRESENTATIONS

**2024** &ensp; “Integrating Imaging Spectroscopy and Elevation in Machine Learning for Soil Salinity Estimation in Coastal Wetlands” Paper,
    Ecological Society of America Annual Meeting <br>
**2023** &ensp; "Remote Predictors of Soil Salinity in an Intermittently Tidal Wetland” Poster, American Geophysical Union Annual Conference  <br>
**2022** &ensp; "Shifts in Salt Marsh Vegetation Landcover After Debris Flow Deposition" Paper, European Spatial Data for Coastal and Marine   Remote Sensing<br>
**2021** &ensp; “Change Detection in Carpinteria Salt Marsh Following the Montecito Debris Flow” Paper, California Geographical Society Conference<br>
**2020** &ensp; “Using Remotely Sensed Data to Map Extent of Debris in a
    Californian Salt Marsh” Poster, National oSTEM Conference <br>
**2019** &ensp; “Pickleweed Vigor in a Californian Salt Marsh: A Remote
    Sensing Approach” Paper, 33rd Annual Student Research Competition at
    CSU Stanislaus <br>
**2018** &ensp; “Effect of California’s Drought on Pickleweed Health in
    Salinas River National Wildlife Refuge: A Remote Sensing Approach”
    Poster, Association of Pacific Coast Geographers<br>

## SERVICE

### University of California, Santa Barbara

Geography Grad Student Peer Mentor &ensp;  **2022 – Present** <br>
California Geographical Society, Student Representative &ensp;  **2022-Present** <br>
Faculty Committee Student Representive &ensp;  **2022-Present** <br>
Outreach Committee &ensp; **2021-2022**<br>
oSTEM Co-President &ensp;  **2021 – 2022**<br>
oSTEM Graduate Student Mentor &ensp;  **2021 – 2022**<br>
oSTEM Graduate Student Liaison &ensp;  **2020 – 2021**<br>
Search Committee, Graduate Student Representative &ensp;**2020**<br>
Geography Awareness Week Presenter &ensp;  **2019**<br>
Geography Student Representative, Graduate Student Association &ensp;   **2019 – 2020**<br>

### California State University, Stanislaus

Campus Tree Interactive Web Map &ensp;**2018**<br>
GIS Intern for Merced County through Office of Service Learning &ensp; **2018**<br>
Student Representative, University Student Union Board of Directors &ensp; **2017 – 2019**<br>
Student Representative, Committee for Sustainable Futures &ensp;  **2017 – 2019**<br>
Gamma Theta Upsilon Honor Society President &ensp;  **2017 – 2019**<br>
Social Media Coordinator, Geography Club &ensp;  **2017 – 2019**<br>
Volunteer, Geocaching activity at Science Day &ensp;  **2017**<br>
Director of Environment, Associated Students, Inc. Board of Directors &ensp;**2016 – 2017**<br>
Treasurer, Geography Club &ensp; **2016 – 17/2018 – 2019**<br>

## MEMBERSHIPS

Ecological Society of America <br>
California Estuarine Research Society <br>
Coastal and Estuarine Research Federation <br>
American Geophysical Union <br>
Out in Science, Technology, Engineering, and Mathematics<br>
American Association for the Advancement of Science<br>
Gamma Theta Upsilon Honor Society<br>
Association of Pacific Coast Geographers <br>
American Association of Geographers <br>
California Geographical Society<br>

## GRANTS & FELLOWSHIPS

Eugene Cota-Robles Fellow, *UC Santa Barbara Graduate Division* &emsp; **Sep 2019 – Present** <br>
UCSB Associated Students Coastal Fund, *\$6515.60* &emsp; **June 2023** <br>
Graduate Research Fellow, *National Science Foundation* &emsp; **Sep 2019 –   Sep 2022** <br>
Ronald E. McNair Scholars Program, *California State University, Stanislaus* &emsp; **Jan 2018 – May 2019**

## AWARDS AND HONORS

*Tom McKnight and Joan Clemons Award for an Outstanding Paper*, Association of Pacific Coast Geographers &emsp; **October 2024** <br>
*1st place Graduate Paper Presentaton*, California Geographical Society &emsp; **April 2024** <br>
*Latinx American Travel Scholarship*, Association of Pacific Coast Geographers &emsp; **October 2023**<br>
*Geosystems Award for Applied/Physical Geography*, Association of Pacific Coast Geographers &emsp; **October 2023**<br>
*Manuscript Monday Highlight*, Ladies of Landsat &emsp; **November 2022**<br>
*Geosystems Award*, California Geographical Society &emsp; **April 2021**    <br>
*First Place Presentation*, 33rd Annual Student Research Competition, California State University, Stanislaus &emsp; **March 2018** <br>
*David Lantis Scholarship Award*, California Geographical Society &emsp;  **April 2018** <br>
