---
title: "Philosophy"
description: |
  Teaching and Diversity Statements
---
# Teaching Philosophy

Geography and environmental sciences are disciplines that examine the world around us. We are all directly and indirectly interacting with our surroundings and the processes and patterns of change in our natural and built environment. Because of these human and environment connections, students—regardless of their background—can connect some aspect of their lives with the academic topics of our disciplines. Indeed, every student is fully capable and deserving of the chance to learn and develop the skills they need to think critically and to examine and communicate ideas about the world around them. My hope is that students in and out of my classroom will find an inclusive and supportive environment that will allow them to make those connections and develop the skills that they need to investigate and think about the world around them. To develop this environment, I strive to embody these ideals in and beyond the classroom through my teaching, mentorship, and research activity. 

## Teaching: Open and Supportive Classrooms for Student Success 

My role as a teacher is to create an environment that allows students to gain the skills and achieve the learning objectives that are set for them. There are many ways in which I fulfill this role. First, I let my students know that I am available and approachable. I achieve this through non-content instructor talk (e.g., sharing personal stories and building sense of community), meeting my students at their skill level, and treating the students with respect and patience. This was reflected in student evaluations where 82% of the responses said I was very approachable and 89% said I was very or quite available showing that I am meeting this teaching goal. Second, I am intentional and considerate of how I can make my curriculum culturally responsive and inclusive. To this end, I consider how class activities and assignments can be more inclusive and connect the content that students are learning more directly to their lived experiences and goals. For example, I have incorporated reflection and discussion of students’ personal experience with class topics, developed inclusive and clear objective writing assignments, and incorporated the responsible use of AI into my teaching of UCSB’s GEOG W8 Introduction to Climate Change. 
I always seek to learn and improve to meet the changing needs of students. I have participated in workshops, classes, and certificate programs, such as UCSBs Certificate in College and University Teaching and Summer Teaching Institute for Associates, with the aim of improving my teaching skills so that I am able to meet the changing demands of student learning needs Trainings have included, but were not limited to, culturally responsive teaching, developing better mentorship practices, translating academic skills to non-academic settings, and course development/prep. Additionally, I actively survey my students for feedback throughout the class, which allows me to adjust lectures and class activities to better meet their needs and allow them to voice their concerns. I am dedicated to improving as I grow my skills as an instructor. 

## Mentorship: Supporting Student Success Outside the Classroom

Supporting student success should not be limited to the classroom. The mentorship that I received was crucial to my success along my academic path. There are many hidden barriers to student success, such as the lack of awareness of academic resources, not understanding how to utilize office hours, or lack of sense of belonging, that may be overcome by mentoring and supporting students outside of the classroom. One of my roles as a mentor is helping students break down these potential barriers, from helping students to navigate the “hidden curriculum” of higher education to helping students connect to campus communities and develop support networks. 
I have mentored students in multiple capacities throughout my academic career. For example, I have mentored undergraduate research projects through the McNair Scholars program and through independent research projects in one of my advisor’s labs that have led to conference presentations and manuscript preparation, outreach opportunities, skill development workshops, and involvement of more students. I have had the opportunity to mentor students on professional development, career pathways, and how to navigate grad school applications. Additionally, I have both formally and informally peer mentored graduate students, which has allowed me to support them as they with navigate the idiosyncrasies of our academic department and university, such as managing fellowship pay or selection of committee members, or developing a sense of place and connection to the department community. Each of these experiences have taught me different lessons and helped me to form my own mentorship style that is student-need centered and goal-oriented, so that I can tailor my mentorship style to support students’ success in the way that most suits their needs.  

## Research: Student Involvement and Application of Skills 

I strive to exemplify excellence in research and that begins by accepting that science is a community effort that requires diverse skill sets and perspectives to succeed. Therefore, student involvement and collaboration are important and critical aspect of my research. Student involvement serves to not only benefit and expand my research program, but also to provide important experiences to students. I have involved students in all steps of the research process from study design and field work for sample collection to data analysis. Student involvement in my research allows students to explore different aspects of our discipline and helps them to explore their interests for future careers, develop their professional networks, and allows them to apply their knowledge and skills in a different context from the classroom. Additionally, their involvement provides me additional opportunities to mentor students, explore additional scientific interests, and provides me examples to strengthen my outreach and engagement with broader groups of students. Thus, involving students helps me become a better researcher and communicator, while empowering students to gain the professional development that they seek. 

I envision being able to teach many classes including, but not limited to, coastal geography, wetland ecology, remote sensing, and environmental data science, as well as advise students on and develop curriculum for spatial and environmental data analysis. Furthermore, I foresee partnering with various university programs and centers, such as the McNair Scholars Program and student resource centers, to support a diverse body of students across campus. 

# Diversity Statement

## Motivations

My commitment to diversity, equity, inclusion, and belonging (DEIB) comes from my personal experiences as a student at both California State University (CSU) and University of California (UC) campuses. As a queer person of color, I found navigating school a challenge, especially as the first in my family to pursue a career in science and my eventual PhD years later. It was especially difficult due to the sense of otherness and initial lack of community that came with attending a school in a conservative town and was amplified by the feeling of disconnection with my biology peers and the notable lack of diversity within the faculty. This impacted my sense of belonging in higher education and science and contributed to my imposter syndrome. However, as I progressed through my academic career, I not only found community and support where I thought there was none, but I also strived to create a sense of community and belonging for others like myself. 

The experiences that contributed to my success as an undergraduate student at Stanislaus State were those that allowed me to be my authentic self, created opportunities to interact with others of diverse backgrounds, and improved my sense of inclusion and belonging. These experiences began with switching my major to Geography and having smaller class sizes and increased interaction with my peers and professors in geography classes. This was further improved by my involvement with the LGBTQ+ Mentorship program that connected me to a community of queer faculty and students on campus and provided me opportunities for professional and social development. Lastly, as a McNair Scholar, I was exposed to research and provided conference and graduate school assistance that helped demystify the “hidden curriculum” of higher education and graduate school. Each of these experiences were critical aspects of helping me develop my sense of belonging and inclusion which improved my confidence as a scientist. 

When I began graduate school at UC Santa Barbara, I found myself without the sense of community, place, and belonging that supported me as an undergraduate student, and I once again felt the lack of diversity in students and faculty within geoscience and environmental sciences, especially an under-representation of Hispanic, Black, queer, and woman-identifying individuals. This led to a sense of duty to find and develop that community for myself and other students. In this capacity, my involvement in DEIB activities changed from a participant to a leader and active member of the community. 

## Action

The first example of my DEIB work at UCSB is my involvement with the local chapter of Out in STEM (oSTEM) as both the graduate student liaison and co-president. In this capacity, I was able to develop programs that supported queer individuals and their allies in STEM majors and programs. Specifically, oSTEM developed a mentorship program where graduate students mentored undergraduate students and, LGBTQ+ graduate student membership grew under my leadership by over 100%. 

A second example of direct DEIB work includes being a member of the Geography Equity Diversity and Inclusion Working Group (GEDIWG). This group of departmental volunteers and DEI committee members was responsible for identifying specific issues within the department, researching supporting literature and examples of correcting those problems, and carrying out those actions. The goal of this group’s actions was to build a more inclusive, anti-racist, and equitable department. During my involvement, I helped draft recommendations and action plans related to graduate and undergraduate student DEIB initiatives within the department, such as the revival of the geography club for undergraduates and graduate student mentorship programs. 

Finally, much of my DEIB work has taken the form of mentoring diverse populations of undergraduate and graduate students. I have mentored a McNair Scholar at UCSB through an independent research project that has resulted in several conference presentations, including an annual meeting of a large national organization, the development of a manuscript, and applying to graduate school. I have also provided graduate school application support to under-represented students by serving as a reviewer for Society for the Advancement of Chicanos/Hispanics and Native Americans in Science (SACNAS) workshops, which allowed me to support a broader community of students on campus beyond my department. My graduate student mentorship within my department has largely taken the form of mentoring junior graduate students and helping them to navigate the program, build a network, and adjust to graduate school in hopes to ultimately help them build a sense of place and belonging in academia. Additionally, I have been a strong advocate for student involvement in regional and student-oriented conferences to support students in building presentation skills and their professional networks. The most successful example of this effort is the Association of Pacific Coast Geographers 2023 annual meeting, where I coordinated the participation of 15 UCSB Geography students, post-docs, and faculty in the meeting, where there had previously been no participation from our department.  

## Future Plans

I envision a continued commitment to fostering a diverse, equitable, and inclusive environment where my students and colleagues have a sense of belonging in academia and STEM fields. As part of establishing my research program, I would leverage various research opportunities to recruit and support students to work with me, such as the McNair Scholars Program and undergrad research funding opportunities. Additionally, I would continue to encourage frequent student participation in regional scientific meetings, such as the Association of Pacific Coast Geographers, California Geographical Society, or California Estuarine Research Society, in addition to on-campus opportunities, whether that be upper division class projects or independent research completed in my or another lab. As these conferences tend to be low cost and smaller in size, attending these regional conferences provides a student-friendly space that allows students to develop important skills for their professional development and have a lower barrier to entry than larger meetings, making them a more equitable and inclusive option for students of varying backgrounds. In my teaching, I hope to bring my training in inclusive teaching, such as culturally-responsive teaching that integrates student experiences into their learning, as well as my experience in executing evidence based pedagogical techniques and assignment development to address new learning and teaching challenges that students will encounter in our rapidly developing world, such as the need to develop AI literacy or critical thinking and writing skills. Lastly, in my service, I anticipate collaborating with different organizations and programs in addition to any DEIB committee work in my home department, to support DEIB work across campus as well as my department. While these are only my initial plans, I believe they represent a holistic approach to fostering DEIB in academia.

