---
title: "Publications"
description: |
  Recent Research Publications
---

# First-Authored Publications

<pre> <b>Silva, G.D.</b> “Leveraging ChatGPT as a tool for teaching AI and climate media literacy”	  <b>In Press</b>         
	  <i>California Geography</i> </pre>
<pre> <b>Silva, G.D.</b>, Roberts, D.A., Byrd, K.B., Chadwick, K.D., Walker, I.J., and King, J.Y.    <b>Aug. 2025</b>               
	  “Using imaging spectroscopy and elevation in machine learning to estimate soil 
  	salinity in intermittently tidal wetlands.” <i>Ecosphere</i> 16 (8): e70356. 
  	https://doi.org/10.1002/ecs2.70356 </pre>
<pre> <b>Silva, G.D.</b>, Roberts, D., McFadden, J., and King, J., “Shifts in Salt Marsh Vegetation    <b>June 2022</b>     
	Landcover Following Debris Flow Deposition.” <i>Remote Sensing</i> 14(12):2819. 
	https://doi.org/10.3390/rs14122819 </pre>

# Co-authored Publications

<pre> Chadwick KD, and many coauthors including <b>Silva, G.D.</b>  “Unlocking ecological             <b>Mar. 2025</b>
    insights from subseasonal visible-to-shortwave infrared imaging spectroscopy:
    The SBG High Frequency Time Series (SHIFT) campaign.” <i>Ecosphere</i> 16 (3). 
    https://doi.org/10.1002/ecs2.70194 </pre>